// Mocks generated by Mockito 5.3.0 from annotations
// in flutter_custom_animation/test/domain/usecase/category/get_all_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_custom_animation/domain/entity/category.dart' as _i4;
import 'package:flutter_custom_animation/domain/service/catagories.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoriesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesService extends _i1.Mock implements _i2.CategoriesService {
  MockCategoriesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Category>> getAllCategories() => (super.noSuchMethod(
          Invocation.method(#getAllCategories, []),
          returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]))
      as _i3.Future<List<_i4.Category>>);
}
